spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/test-pg-db
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
