version: '3.8'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-pg-db

  adminer:
    image: adminer
    restart: always
    ports:
      - "80:8080"